import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import BottomNav from "@/components/ui/bottom-nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-black text-black dark:text-white transition-all duration-300 grid grid-rows-[auto_1fr_auto] min-h-dvh`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <header>text</header>
          <main>
            {children}
          </main>
          <BottomNav
            items={[
              { label: "Home", href: "/" },
              { label: "About", href: "/about" },
              { label: "Projects", href: "/projects"},
              { label: "Contact", href: "/contact"},
            ]}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
